// <auto-generated />
namespace MonedaCubana.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class cambiandoeltamannoeneldataanottationdelmodelopersona : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cambiandoeltamannoeneldataanottationdelmodelopersona));
        
        string IMigrationMetadata.Id
        {
            get { return "201805261519384_cambiando el tamanno en el data anottation del modelo persona"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
